<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <MPL>
      <AbsolutePaths>false</AbsolutePaths>
      <AdditionalDependencies Condition="$(Configuration)==assert">legacy_stdio_definitions.lib;libcmt.lib;oldnames.lib</AdditionalDependencies>
      <AdditionalDependencies Condition="$(Configuration)==debug">legacy_stdio_definitions.lib;msvcrtd.lib;oldnames.lib</AdditionalDependencies>
      <AdditionalDependencies Condition="$(Configuration)==release">legacy_stdio_definitions.lib;libcmt.lib;oldnames.lib</AdditionalDependencies>
      <CallTrace Condition="$(Configuration)==assert">SingleThreaded</CallTrace>
      <CallTrace Condition="$(Configuration)==debug">SingleThreaded</CallTrace>
      <CallTrace Condition="$(Configuration)==release">None</CallTrace>
      <CompilationMode>Regular</CompilationMode>
      <CompilerPath>mplc</CompilerPath>
      <Definitions Condition="$(Configuration)==assert">DEBUG=TRUE</Definitions>
      <DisableDebugInfo Condition="$(Configuration)==assert">true</DisableDebugInfo>
      <DisableDebugInfo Condition="$(Configuration)==debug">false</DisableDebugInfo>
      <DisableDebugInfo Condition="$(Configuration)==release">true</DisableDebugInfo>
      <MinimalRebuildFromTracking>true</MinimalRebuildFromTracking>
      <PointerSize Condition="$(Platform)==win32">32</PointerSize>
      <PointerSize Condition="$(Platform)==x64">64</PointerSize>
      <ShowMemoryUsage>false</ShowMemoryUsage>
    </MPL>
  </ItemDefinitionGroup>
</Project>
